name: honours-project
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py[build=mpi*]
  - c-compiler
  - matplotlib
  - ipykernel
  - ffmpeg
  - dask
  - xarray=2023.4.2
  - xesmf
  - netcdf4
  - h5netcdf
  - pylint
  - flake8
  - jupyter-server-proxy
  - xrft
  - statsmodels
  - adjusttext
variables:
  OMP_NUM_THREADS: '1'
  NUMEXPR_MAX_THREADS: '1'
