# Low Ra run to create initial condition

equations:
    class: !!python/name:modules.models.DNS

initial_condition:
    type: prescribed

logfile: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/init/init.log

output:
    dir: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/init
    max_writes: 2400
    save_sim_time: 0.2

parameters:
    aspect: 8.0
    nx: 256
    nz: 32
    prandtl: 1.0
    rayleigh: 1.0e+7

run:
    sim_time: 50
    timestep: 8.0e-3
