# Resolution dependence experiments (up to 1024x128)

base:
    equations:
        class: !!python/name:modules.models.NonlinearHyperviscosity
        hyper: 1.0e-3
        delta_nu: 2.0e-3
    parameters:
        aspect: 8.0
        nx: 1024  # changes
        nz: 128  # changes
        rayleigh: 1.0e+9
        prandtl: 1.0
    initial_condition:
        type: interpolate
        file: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/init/init_s1.nc
        time: 50.0
    output:
        dir: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/resolution_tests/1024x128  # changes
        save_sim_time: 0.2
        max_writes: 300  # changes
    run:
        sim_time: 1000
        timestep: 2.0e-3  # changes
    logfile: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/resolution_tests/1024x128/1024x128.log  # changes

runs:
    - [256, 64]
    - [512, 64]
    - [768, 96]
    - [1024, 128]
