# Simulations for generating the training dataset

fine:
    equations:
        class: !!python/name:modules.models.NonlinearHyperviscosity
        hyper: 2.0e-3
        delta: 2.0e-3
    parameters:
        aspect: 8.0
        nx: 2048
        nz: 256
        rayleigh: 1.0e+9
        prandtl: 1.0
    initial_condition:
        type: interpolate
        file: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/resolution_tests/2048x256/*.nc
        time: 350.
    output:
        dir: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/fine/time_t
        save_sim_time: 3.0
        max_writes: 75
    pair_output:
        dir: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/fine/time_tplusdt
    run:
        sim_time: 300.
        timestep: 1.0e-3
    logfile: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/fine/fine.log

coarse_graining_t:
    parameters: &cg_params
        aspect: 8.0
        to_nx: 256
        to_nz: 64
        run_time: 1.0e-3
        run_dt: 2.0e-4
    input: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/fine/time_t/*.nc
    output: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/coarse_grained/time_t.nc
    logfile: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/coarse_grained/time_t.log

coarse_graining_tplusdt:
    parameters: *cg_params
    input: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/fine/time_tplusdt/*.nc
    output: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/coarse_grained/time_tplusdt.nc
    logfile: /srv/ccrc/AtmSS/z5310829/honours_project/final_data/training_data/coarse_grained/time_tplusdt.log
